config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tests do
    resources :questions, shallow: true
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  MAX_ANSWERS = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_count

  private

  def validate_answers_count
    if question && question.answers.size >= MAX_ANSWERS
      errors.add(:count, "Максимальное количество ответов: #{MAX_ANSWERS}")
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :questions
  has_many :tests_users
  has_many :users, through: :tests_users

  scope :easy_level, -> { where(level: 0..1) }
  scope :normal_level, -> { where(level: 2..4) }
  scope :hard_level, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }

  validates :title, presence: true, uniqueness: { case_sensitive: false, scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.titles_by_category_title(title)
    by_category(title).order(title: :desc).pluck(:title)
  end
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :tests_users
  has_many :tests, through: :tests_users
  has_many :created_tests, class_name: 'Test', foreign_key: 'user_id'

  validates :email, presence: true

  def tests_by_level(level)
    tests.where(level: level)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :find_test, only: %i[index create new]
  before_action :find_question, only: %i[destroy show]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @questions = @test.questions
  end

  def show; end

  def new; end

  def create
    question = @test.questions.new(question_params)

    if question.save
      redirect_to question
    else
      render :new
    end
  end

  def destroy
    @question.destroy

    redirect_to test_questions_path(test_id: @question.test_id)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1><%= @test.title %></h1>

<ul>
  <% @questions.each do |question| %>
    <li>
      <strong><%= link_to question.body, question %></strong><br />
      <%= link_to "Удалить", question, method: :delete %>
    </li>
  <% end %>
</ul>

<p>
    <%= link_to "Создать вопрос", new_test_question_path %>
</p>

app/views/questions/new.html.erb
<h1>Создание вопроса</h1>

<form action="/tests/<%= params[:test_id] %>/questions" method="post">
  <input type="hidden" value="<%= form_authenticity_token %>">

  <p>
    <label id="question-body">Текст вопроса:</label>
    <input type="text" name="question[body]" id="question-body" />
  </p>

  <p>
    <input type="submit" value="Создать вопрос" />
  </p>
</form> 

app/views/questions/show.html.erb
<p><%= @question.body %></p> 